name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Node dependencies if package.json exists
        run: |
          if [ -f package.json ]; then
            npm ci
          else
            echo "No package.json file found. Skipping Node dependency installation."
          fi

      - name: Install Python dependencies if requirements.txt exists
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          else
            echo "No requirements.txt file found. Skipping Python dependency installation."
          fi

      - name: Run tests
        run: echo "No tests configured for this project."
